name: monify
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  connectivity_plus: ^6.0.2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.2.6
  gap: ^3.0.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  fl_chart: ^0.67.0
  json_annotation: ^4.8.1
  intl: ^0.19.0
  cloud_firestore: ^4.16.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  json_serializable: ^6.7.1


flutter:


  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 400
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 600


